"""UI text constants for the VOTRYX interface."""

STRINGS = {
    "header_title": "VOTRYX Control Panel",
    "header_subtitle": "Automated voting controller",
    "state_idle": "Idle",
    "section_status": "Status",
    "stat_votes": "Votes",
    "stat_errors": "Errors",
    "stat_state": "State",
    "stat_runtime": "Runtime",
    "section_settings": "Settings",
    "section_general": "General",
    "label_target_url": "Target URL",
    "helper_target_url": "Voting page URL",
    "label_vote_interval": "Vote Interval (sec)",
    "helper_vote_interval": "Delay between votes",
    "label_batch_size": "Batch Size",
    "helper_batch_size": "Votes per batch",
    "label_timeout": "Timeout (sec)",
    "helper_timeout": "Vote button wait limit",
    "label_max_errors": "Max Errors",
    "helper_max_errors": "Backoff after consecutive errors",
    "label_backoff": "Backoff (sec)",
    "helper_backoff": "Initial backoff delay",
    "label_backoff_cap": "Backoff Cap",
    "helper_backoff_cap": "Max backoff delay",
    "label_parallel": "Parallel Windows",
    "helper_parallel": "Browser count",
    "toggle_headless": "Run headless",
    "toggle_auto_driver": "Use Selenium Manager",
    "helper_headless": "Headless mode hides Chrome windows. Selenium Manager auto-resolves drivers.",
    "section_advanced": "Advanced",
    "toggle_random_ua": "Randomize user agent",
    "helper_random_ua": "Uses custom list or defaults when enabled.",
    "toggle_block_images": "Block images for faster loads",
    "helper_block_images": "When enabled, image loading is disabled.",
    "label_user_agents": "User-Agent list (one per line)",
    "helper_user_agents": "Leave empty for defaults.",
    "label_vote_selectors": "Vote selectors (CSS or XPath per line)",
    "helper_vote_selectors": "Example: css:a[data-action='vote'] or xpath://button[contains(.,'vote')]",
    "button_apply": "Apply Settings",
    "button_defaults": "Reset Defaults",
    "section_log": "Log",
    "badge_success": "Success",
    "badge_errors": "Errors",
    "toggle_autoscroll": "Autoscroll",
    "toggle_errors_only": "Errors only",
    "button_clear_log": "Clear Log",
    "section_actions": "Actions",
    "button_start": "Start",
    "button_stop": "Stop",
    "button_preflight": "Preflight",
    "button_open_logs": "Open Logs",
    "button_reset_counters": "Reset Counters",
    "button_tray": "Minimize to Tray",
    "welcome_title": "Welcome to VOTRYX",
    "welcome_subtitle": "A focused workspace for automated voting control.",
    "welcome_bullets": [
        "Guided setup for URL, timing, and batch size.",
        "Live status, counters, and log visibility.",
        "Guardrails for errors, backoff, and recovery.",
    ],
    "welcome_cta": "Start Setup",
    "tutorial_title": "Quick Start",
    "tutorial_subtitle": "Three steps to launch a clean voting session.",
    "tutorial_steps": [
        "1) Set Target URL and timing in Settings.",
        "2) Run Preflight to confirm driver and Chrome.",
        "3) Press Start and monitor Status + Log.",
    ],
    "tutorial_cta": "Open Control Panel",
}
